### ISSUE TITLE
Death of Akagi caused server crash

### ISSUE THREAD

**Issue by loveyanbei** [PinkaLulan/ShinColle#27]
Spongeforge - 1.10.2-2281-5.2.0-BETA-2274
/*****************************************************************************************************************/
/* Expected to exit phase: EntityTickPhase                                                                       */
/* But instead found phase: org.spongepowered.common.event.tracking.phase.entity.DeathUpdateState@660c6443       */
/* StackTrace:                                                                                                   */
/* java.lang.Exception: null                                                                                     */
/*     org.spongepowered.common.event.tracking.CauseTracker.printIncorrectPhaseCompletion(CauseTracker.java:272) */
/*     org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:194)                 */
/*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:164)                    */
/*     net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjp000(WorldServer.java:2815)                 */
/*     net.minecraft.world.World.func_72866_a(World.java:4072)                                                   */
/*     net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)                                        */
/*     net.minecraft.world.World.func_72870_g(World.java:1934)                                                   */
/*     net.minecraft.world.World.func_72939_s(World.java:5957)                                                   */
/*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2157)                                       */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)                               */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)                     */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)                               */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                        */
/*     java.lang.Thread.run(Thread.java:745)                                                                     */
/*  Phases Remaining:                                                                                            */
/*   - Phase: org.spongepowered.common.event.tracking.phase.entity.DeathUpdateState@660c6443                     */
/*     Context:                                                                                                  */
/*     - Name: CapturedBlocks                                                                                    */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                              */
/*     - Name: CapturedEntities                                                                                  */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                            */
/*     - Name: Source                                                                                            */
/*       Object: EntityCarrierAkagi['Standard Carrier Akagi'/627, l='world', x=-1478.54, y=76.00,                */
/*       z=6613.93]                                                                                              */
/*   - Phase: EntityTickPhase                                                                                    */
/*     Context:                                                                                                  */
/*     - Name: Source                                                                                            */
/*       Object: EntityCarrierAkagi['Standard Carrier Akagi'/627, l='world', x=-1478.54, y=76.00,                */
/*       z=6613.93]                                                                                              */
/*     - Name: CapturedEntities                                                                                  */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                            */
/*     - Name: CapturedBlocks                                                                                    */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                              */
/*     - Name: Notifier                                                                                          */
/*       Object: EntityPlayerMP['lyt'/522, l='world', x=-1490.33, y=76.00, z=6639.23]                            */
/*     - Name: Owner                                                                                             */
/*       Object: EntityPlayerMP['lyt'/522, l='world', x=-1490.33, y=76.00, z=6639.23]                            */
/*                                                                                                               */
/* Minecraft : 1.10.2                                                                                            */
/* SpongeAPI : 5.2.0-SNAPSHOT-a3257a0                                                                            */
/* SpongeForge : 1.10.2-2281-5.2.0-BETA-2274                                                                     */
/* Minecraft Forge : 12.18.3.2281                                                                                */
/*****************************************************************************************************************/

[16:41:42] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at com.lulan.shincolle.utility.EntityHelper.getPetPlayerUUID(EntityHelper.java:516) ~[EntityHelper.class:?]
        at com.lulan.shincolle.entity.BasicEntityShip.func_70609_aI(BasicEntityShip.java:6140) ~[BasicEntityShip.class:?]
        at net.minecraft.entity.EntityLivingBase.onSpongeDeathUpdate(EntityLivingBase.java:3636) ~[sf.class:?]
        at net.minecraft.entity.EntityLivingBase.redirect$causeTrackDeathUpdate$zda000(EntityLivingBase.java:3626) ~[sf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:314) ~[sf.class:?]
        at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208) ~[sg.class:?]
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359) ~[rw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932) ~[sf.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[sg.class:?]
        at com.lulan.shincolle.entity.BasicEntityShip.func_70071_h_(BasicEntityShip.java:2493) ~[BasicEntityShip.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:159) ~[TrackingUtil.class:1.10.2-2281-5.2.0-BETA-2274]
        at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjp000(WorldServer.java:2815) ~[ls.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:4072) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) ~[ls.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1934) ~[aid.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:5957) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2157) ~[ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by loveyanbei** [comment]
When I killed a ship spawned from enderio soul bottle, the server went crashed,
The reason maybe:
public static String getPetPlayerUUID(EntityTameable pet)
	{
		if (pet != null)
		{
		//	if(pet.getOwnerId() != null)
		//	{
			    return pet.getOwnerId().toString();   //here -> getOwnerId returns null
		//	}
		//	else
		//	{
		//		return "00000000-0000-0000-0000-000000000000"; //dummy uuid on special condition
		//	}
		}
		
		return null;
	}

**Comment by loveyanbei** [comment]
Pull Request was sent

**Comment by PinkaLulan** [comment]
bug confirmed, thank you!
