### ISSUE TITLE
crash report 1.10.2 -- Kill wild Heavy Cruiser Atago or wild Heavy Cruiser Takao

### ISSUE THREAD

**Issue by SuanRaymond** [PinkaLulan/ShinColle#48]
Kill wild Heavy Cruiser Atago or wild Heavy Cruiser Takao

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.254-ex110.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 2018/2/6 上午 3:34
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.lulan.shincolle.entity.cruiser.EntityCAAtagoMob.func_70097_a(EntityCAAtagoMob.java:87)
	at com.lulan.shincolle.utility.BuffHelper.applyBuffOnTicks(BuffHelper.java:341)
	at com.lulan.shincolle.entity.BasicEntityShipHostile.func_70636_d(BasicEntityShipHostile.java:911)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52)
	at com.lulan.shincolle.entity.BasicEntityShipHostile.func_70071_h_(BasicEntityShipHostile.java:820)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1937)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.lulan.shincolle.entity.cruiser.EntityCAAtagoMob.func_70097_a(EntityCAAtagoMob.java:87)
	at com.lulan.shincolle.utility.BuffHelper.applyBuffOnTicks(BuffHelper.java:341)
	at com.lulan.shincolle.entity.BasicEntityShipHostile.func_70636_d(BasicEntityShipHostile.java:911)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52)
	at com.lulan.shincolle.entity.BasicEntityShipHostile.func_70071_h_(BasicEntityShipHostile.java:820)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1937)

-- Entity being ticked --
Details:
	Entity Type: shincolle.EntityCruiserAtagoMob (com.lulan.shincolle.entity.cruiser.EntityCAAtagoMob)
	Entity ID: 1447
	Entity Name: Heavy Cruiser Atago
	Entity's Exact location: 61.90, 62.65, 195.17
	Entity's Block location: World: (61,62,195), Chunk: (at 13,3,3 in 3,12; contains blocks 48,0,192 to 63,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 847 Drop: 0
	Level seed: -698415788597033817
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (236,64,224), Chunk: (at 12,4,0 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 20660534 game time, 21098025 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 51305 (now: false), thunder time: 33270 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)

**Comment by PinkaLulan** [comment]
fixed in 1.10.2.7.1
