### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by Xiazihong** [PinkaLulan/ShinColle#52]
please delete

**Comment by Xiazihong** [comment]
21:06:26] [User Authenticator #1/INFO]: UUID of player Suu_Q is 179099ad-4f32-3792-931f-cadb3e444cce
[21:06:26] [Server thread/INFO]: DEBUG : entity constructing: on player constructing 154 EntityPlayerMP
[21:06:32] [Netty IO #3/INFO]: Client protocol version 2
[21:06:32] [Netty IO #3/INFO]: Client attempting to join with 22 mods : NotEnoughItems@1.0.4.83,Thaumcraft@4.2.3.5,UnicodeFontFixer@1.0.4,InputFix@1.7.x-v2,FML@7.10.99.99,vexview@1.1,customnpcs@1.7.10d,Forge@10.13.4.1614,NBTEdit@1.7.2.2,Baubles@1.0.1.10,kbh@1.0.0,CodeChickenCore@1.0.4.35,ThaumicTinkerer@unspecified,ForbiddenMagic@1.7.10-0.575,Botania@r1.8-249,mcp@9.05,ThaumicTinkerer-preloader@0.1,DamageIndicatorsMod@3.2.0,shincolle@1.7.10.rv26.2,craftguide@1.6.8.1,UraniumPlus@1.0,FpsReducer@1.7.10-1.7
[21:06:32] [Netty IO #3/INFO]: Attempting connection with missing mods [kimagine] at CLIENT
[21:06:32] [Server thread/INFO]: [Server thread] Server side modded connection established
[21:06:32] [Server thread/ERROR]: Failed to load extended properties for TeitokuExtProps.  This is a mod issue.
[21:06:32] [Server thread/WARN]: java.util.UnknownFormatConversionException: Conversion = '"'
[21:06:32] [Server thread/WARN]: 	at java.util.Formatter.checkText(Unknown Source)
[21:06:32] [Server thread/WARN]: 	at java.util.Formatter.parse(Unknown Source)
[21:06:32] [Server thread/WARN]: 	at java.util.Formatter.format(Unknown Source)
[21:06:32] [Server thread/WARN]: 	at java.util.Formatter.format(Unknown Source)
[21:06:32] [Server thread/WARN]: 	at java.lang.String.format(Unknown Source)
[21:06:32] [Server thread/WARN]: 	at cpw.mods.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:60)
[21:06:32] [Server thread/WARN]: 	at cpw.mods.fml.common.FMLLog.log(FMLLog.java:25)
[21:06:32] [Server thread/WARN]: 	at com.lulan.shincolle.utility.LogHelper.log(LogHelper.java:14)
[21:06:32] [Server thread/WARN]: 	at com.lulan.shincolle.utility.LogHelper.info(LogHelper.java:36)
[21:06:32] [Server thread/WARN]: 	at com.lulan.shincolle.entity.ExtendPlayerProps.loadNBTData(ExtendPlayerProps.java:182)
[21:06:32] [Server thread/WARN]: 	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1650)
[21:06:32] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:314)
[21:06:32] [Server thread/WARN]: 	at net.minecraft.server.management.ServerConfigurationManager.func_72380_a(ServerConfigurationManager.java:320)
[21:06:32] [Server thread/WARN]: 	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:148)
[21:06:32] [Server thread/WARN]: 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190)
[21:06:32] [Server thread/WARN]: 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465)
[21:06:32] [Server thread/WARN]: 	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21)
[21:06:32] [Server thread/WARN]: 	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[21:06:32] [Server thread/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[21:06:32] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[21:06:32] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[21:06:32] [Server thread/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[21:06:32] [Server thread/WARN]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[21:06:32] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[21:06:32] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[21:06:32] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[21:06:32] [Server thread/WARN]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[21:06:32] [Server thread/WARN]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[21:06:32] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[21:06:32] [Server thread/WARN]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:176)
[21:06:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989)
[21:06:32] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458)
[21:06:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806)
[21:06:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665)
[21:06:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:06:32] [Server thread/INFO]: Suu_Q[/183.53.65.233:42512] logged in with entity id 154 at ([world] -22.427548192010658, 64.0, 238.38930770654108)
[21:06:33] [Server thread/INFO]: DEBUG : player login: Suu_Q 179099ad-4f32-3792-931f-cadb3e444cce
[21:06:33] [Server thread/INFO]: DEBUG : update player: Suu_Q 179099ad-4f32-3792-931f-cadb3e444cce 154
[21:06:33] [Server thread/INFO]: DEBUG : update player: create pid: 103 eid: 154
[21:06:33] [Server thread/INFO]: DEBUG : server proxy: set next player id 104
[21:06:33] [Server thread/INFO]: DEBUG : player login: save player extProps in ServerProxy
[21:06:33] [Server thread/INFO]: DEBUG : save player ExtNBT: 0
[21:06:33] [Server thread/INFO]: DEBUG : save player ExtNBT: 0
[21:06:33] [Server thread/INFO]: DEBUG : save player ExtNBT: 0
[21:06:33] [Server thread/INFO]: DEBUG : save player ExtNBT: 0
[21:06:33] [Server thread/INFO]: DEBUG : save player ExtNBT: 0
[21:06:33] [Server thread/INFO]: DEBUG : save player ExtNBT: 0
[21:06:33] [Server thread/INFO]: DEBUG : save player ExtNBT: 0
[21:06:33] [Server thread/INFO]: DEBUG : save player ExtNBT: 0
[21:06:33] [Server thread/INFO]: DEBUG : save player ExtNBT: 0
[21:06:33] [Server thread/INFO]: DEBUG : save player ExtNBT data on id: 154
[21:06:33] [Server thread/INFO]: DEBUG : player saveNBTData: backup player extProps in ServerProxy
[21:06:43] [Server thread/INFO]: DEBUG : player tick: update team entity
