### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by lsz7575** [PinkaLulan/ShinColle#8]
palse --help me--。。thank you。。
## 1.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2/17/16 6:41 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
at com.lulan.shincolle.utility.EntityHelper.getEntityPlayerByUID(EntityHelper.java:386)
at com.lulan.shincolle.utility.EntityHelper.getEntityPlayerByUID(EntityHelper.java:378)
at com.lulan.shincolle.proxy.ServerProxy.updateServerTick(ServerProxy.java:628)
at com.lulan.shincolle.handler.FML_COMMON_EventHandler.serverTick(FML_COMMON_EventHandler.java:551)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_105_FML_COMMON_EventHandler_serverTick_ServerTickEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:851)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
at java.lang.Thread.run(Thread.java:745)
A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Linux (amd64) version 3.13.0-32-generic
Java Version: 1.7.0_80, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1986832568 bytes (1894 MB) / 4658298880 bytes (4442 MB) up to 11185160192 bytes (10667 MB)
JVM Flags: 3 total; -XX:+AggressiveOpts -Xms2000m -Xmx12000m
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 2, tcache: 2035, allocated: 1, tallocated: 334
FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1388 15 mods loaded, 15 mods active
mcp{9.05} Minecraft Coder Pack Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
FML{7.10.114.1388} Forge Mod Loader Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Forge{10.13.3.1388} Minecraft Forge Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
AntiCheat3{AntiCheat3} AntiCheat3 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
armourersWorkshop{1.7.10-0.38.1.98} Armourer's Workshop Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
plushieWrapper{0.0.0} Plushie Wrapper Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Baubles{1.0.1.10} Baubles Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Botania{r1.8-247} Botania Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
net.blacklab.lib{0.1.1.forge1121} EBLib Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
GrimoireOfGaia{1.0.0} Grimoire of Gaia 3 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ayamitsu.mobconfinement{2.3.forge1121} MobConfinement_EB Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
shincolle{1.7.10.rv22} Shinkeiseikan Collection Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
flammpfeil.slashblade{mc1.7.10-r75} SlashBlade Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
TwilightForest{2.3.7} The Twilight Forest Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
zeldaswordskills{1.7.10-2.4} Zelda Sword Skills Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 11 / 66; [EntityPlayerMP'yuuyou'/713, l='world', x=1838.32, y=195.00, z=-958.37, EntityPlayerMP'Animadvert'/993, l='world', x=35.94, y=72.00, z=406.49, EntityPlayerMP'fengzhongxiaozhu'/1057, l='world', x=36.89, y=72.00, z=404.04, EntityPlayerMP'511511'/1145, l='DIM7', x=-2906.54, y=88.44, z=474.92, EntityPlayerMP'skyfucker'/1366, l='world', x=-773.44, y=119.00, z=230.02, EntityPlayerMP'ShenHuna'/1771, l='world', x=1218.01, y=64.00, z=51.19, EntityPlayerMP'Wilian'/3137, l='world', x=38.22, y=72.00, z=403.83, EntityPlayerMP'XIAOXUAN'/4332, l='world', x=-582.92, y=74.49, z=1949.51, EntityPlayerMP'Aaron_Boy'/4517, l='world', x=-574.78, y=67.00, z=1990.97, EntityPlayerMP'sky_XiZong'/4873, l='DIM7', x=-1437.42, y=34.02, z=250.77, EntityPlayerMP'mu_xuan'/1517, l='world', x=-1459.51, y=57.00, z=-65.93]
Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
Type: Dedicated Server (map_server.txt)
## 2.

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2/17/16 7:39 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
at com.lulan.shincolle.utility.EntityHelper.getEntityPlayerByUID(EntityHelper.java:386)
at com.lulan.shincolle.utility.EntityHelper.getEntityPlayerByUID(EntityHelper.java:378)
at com.lulan.shincolle.ai.EntityAIShipGuarding.(EntityAIShipGuarding.java:100)
at com.lulan.shincolle.entity.BasicEntityShip.setAIList(BasicEntityShip.java:293)
at com.lulan.shincolle.entity.hime.EntityNorthernHime.setAIList(EntityNorthernHime.java:70)
at com.lulan.shincolle.entity.BasicEntityShip.func_70636_d(BasicEntityShip.java:1563)
at com.lulan.shincolle.entity.BasicEntityShipLarge.func_70636_d(BasicEntityShipLarge.java:81)
at com.lulan.shincolle.entity.hime.EntityNorthernHime.func_70636_d(EntityNorthernHime.java:189)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
at com.lulan.shincolle.entity.BasicEntityShip.func_70071_h_(BasicEntityShip.java:1434)
at net.minecraft.world.World.func_72866_a(World.java:2674)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
at net.minecraft.world.World.func_72870_g(World.java:2623)
at net.minecraft.world.World.func_72939_s(World.java:2423)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
at java.lang.Thread.run(Thread.java:745)
A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at com.lulan.shincolle.utility.EntityHelper.getEntityPlayerByUID(EntityHelper.java:386)
at com.lulan.shincolle.utility.EntityHelper.getEntityPlayerByUID(EntityHelper.java:378)
at com.lulan.shincolle.ai.EntityAIShipGuarding.(EntityAIShipGuarding.java:100)
at com.lulan.shincolle.entity.BasicEntityShip.setAIList(BasicEntityShip.java:293)
at com.lulan.shincolle.entity.hime.EntityNorthernHime.setAIList(EntityNorthernHime.java:70)
at com.lulan.shincolle.entity.BasicEntityShip.func_70636_d(BasicEntityShip.java:1563)
at com.lulan.shincolle.entity.BasicEntityShipLarge.func_70636_d(BasicEntityShipLarge.java:81)
at com.lulan.shincolle.entity.hime.EntityNorthernHime.func_70636_d(EntityNorthernHime.java:189)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
at com.lulan.shincolle.entity.BasicEntityShip.func_70071_h_(BasicEntityShip.java:1434)
at net.minecraft.world.World.func_72866_a(World.java:2674)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
at net.minecraft.world.World.func_72870_g(World.java:2623)

-- Entity being ticked --
Details:
Entity Type: shincolle.EntityNorthernHime (com.lulan.shincolle.entity.hime.EntityNorthernHime)
Entity ID: 13828
Entity Name: Northern Princess
Entity's Exact location: 1435.60, 122.00, 1300.50
Entity's Block location: World: (1435,122,1300), Chunk: (at 11,7,4 in 89,81; contains blocks 1424,0,1296 to 1439,255,1311), Region: (2,2; contains chunks 64,64 to 95,95, blocks 1024,0,1024 to 1535,255,1535)
Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:2423)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)

-- Affected level --
Details:
Level name: world
All players: 8 total; [EntityPlayerMP'Yan_lang'/685, l='world', x=58.89, y=72.00, z=392.71, EntityPlayerMP'Ghost'/1369, l='world', x=52.24, y=72.00, z=397.76, EntityPlayerMP'fengzhongxiaozhu'/2040, l='world', x=40.66, y=72.00, z=409.26, EntityPlayerMP'Wilian'/3853, l='world', x=53.08, y=72.00, z=389.35, EntityPlayerMP'Ben_QAQ'/4597, l='world', x=53.83, y=74.69, z=400.64, EntityPlayerMP'ShenHuna'/6273, l='world', x=55.33, y=72.00, z=389.92, EntityPlayerMP'sky_XiZong'/7962, l='world', x=1218.43, y=64.00, z=56.01, EntityPlayerMP'Animadvert'/5060, l='world', x=1434.00, y=122.00, z=1315.00]
Chunk stats: ServerChunkCache: 436 Drop: 0
Level seed: 3075215524609631789
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options:
Level spawn location: World: (40,72,409), Chunk: (at 8,4,9 in 2,25; contains blocks 32,0,400 to 47,255,415), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 183101536 game time, 183407946 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 17185 (now: true), thunder time: 109522 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
Minecraft Version: 1.7.10
KCauldron Version: pw.prok:KCauldron:1.7.10-1614.200 Official
Plugins: WorldBorder, ResidenceAssist, GroupManager, PlugMan, LimitEnchantment, TabPrefixFix, ColorChat, PermissionsDisable, Skript, Vault, BriberyMoney, Multiverse-Core, iControlU, Multikills, EpicGuild, AntiBoneDustBug, CustomJoinItems, VipZeroFIX, SaveIt, Lottery, SQLibrary, CoreProtect, ChatLib, VipZero, OpenInv, SafeNetherDoor, PlayerPoints, ProtocolLib, AutoRespawn, ProtectDrop, HolographicDisplays, ColorMOTD, RestartAnnounce, LoginMessage, BanItem, Essentials, Residence, EssentialsProtect, EssentialsSpawn, EssentialsAntiBuild, AuthMe, ChestCommands, InfoBoardReborn, EssentialsChat, WaterLimiter
Disabled Plugins:
Operating System: Linux (amd64) version 3.13.0-32-generic
Java Version: 1.7.0_80, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1467704664 bytes (1399 MB) / 3144679424 bytes (2999 MB) up to 11185160192 bytes (10667 MB)
JVM Flags: 3 total; -XX:+AggressiveOpts -Xms2000m -Xmx12000m
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 16 mods loaded, 16 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.05} Minecraft Coder Pack
UCHIJAAAA FML{7.10.99.99} Forge Mod Loader
UCHIJAAAA Forge{10.13.4.1614} Minecraft Forge
UCHIJAAAA kimagine{0.2} KImagine
UCHIJAAAA AntiCheat3{AntiCheat3} AntiCheat3
UCHIJAAAA armourersWorkshop{1.7.10-0.38.1.98} Armourer's Workshop
UCHIJAAAA plushieWrapper{0.0.0} Plushie Wrapper
UCHIJAAAA Baubles{1.0.1.10} Baubles
UCHIJAAAA Botania{r1.8-247} Botania
UCHIJAAAA net.blacklab.lib{0.1.1.forge1121} EBLib
UCHIJAAAA GrimoireOfGaia{1.0.0} Grimoire of Gaia 3
UCHIJAAAA ayamitsu.mobconfinement{2.3.forge1121} MobConfinement_EB
UCHIJAAAA shincolle{1.7.10.rv22} Shinkeiseikan Collection
UCHIJAAAA flammpfeil.slashblade{mc1.7.10-r75} SlashBlade
UCHIJAAAA TwilightForest{2.3.7} The Twilight Forest
UCHIJAAAA zeldaswordskills{1.7.10-2.4} Zelda Sword Skills
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 9 / 66; [EntityPlayerMP'Yan_lang'/685, l='world', x=58.89, y=72.00, z=392.71, EntityPlayerMP'ZhizihuaK'/836, l='ziyuan', x=4406.13, y=33.69, z=4240.43, EntityPlayerMP'Ghost'/1369, l='world', x=52.24, y=72.00, z=397.76, EntityPlayerMP'fengzhongxiaozhu'/2040, l='world', x=40.66, y=72.00, z=409.26, EntityPlayerMP'Wilian'/3853, l='world', x=53.08, y=72.00, z=389.35, EntityPlayerMP'Ben_QAQ'/4597, l='world', x=53.83, y=74.69, z=400.64, EntityPlayerMP'ShenHuna'/6273, l='world', x=55.33, y=72.00, z=389.92, EntityPlayerMP'sky_XiZong'/7962, l='world', x=1218.43, y=64.00, z=56.01, EntityPlayerMP'Animadvert'/5060, l='world', x=1434.00, y=122.00, z=1315.00]
Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
Type: Dedicated Server (map_server.txt)

抱歉走到源码位置评论了，因为我看不懂英文-  =。。原来这边才是反馈的。。

Sorry position went to the source of the comment, because I do not understand English - =. . Here is the original feedback. .

**Comment by liach** [comment]
Actually adding a line of 

``` java
if (world == null) return null;
```

before https://github.com/PinkaLulan/ShinColle/blob/master/src/main/java/com/lulan/shincolle/utility/EntityHelper.java#L386 would fix this bug.
